### ISSUE TITLE
CCC Bug: Inconsistent cell type annotation

### ISSUE THREAD

**Issue by boyiguo1** [LieberInstitute/DLPFC_snRNAseq#20]
Part of CCC analysis (#19)

Bug: Inconsistent var name for cellType annotation:
We use `cellType_hc` != "drop" to drop cells, but use `cellType_broad_hc` as cell type annotation in LIANA
https://github.com/boyiguo1/DLPFC_snRNAseq/blob/5d10ae022ccd577feee7f88230c604619a327511/Boyi_R/CCC_with_LIANA.R#L47
https://github.com/boyiguo1/DLPFC_snRNAseq/blob/5d10ae022ccd577feee7f88230c604619a327511/Boyi_R/CCC_with_LIANA.R#L71

## TODO:

- [ ] Use consistent cell type annotation in cell filtering and LIANA
- [ ] Run LIANA again
    - [x] Reduce the max mem for JHPCE to 20 GB ()
